apiVersion: v1
kind: Namespace
metadata:
  name: gustavoc
  labels:
    istio-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-deployment
  namespace: gustavoc
  labels:
    app: mi-app
    areanegocio: tecnologia
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mi-app
  template:
    metadata:
      labels:
        app: mi-app
    spec:
      containers:
        - name: contenedor-principal
          image: guscontre1/holamundoclase:3
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "500m"
              memory: "800Mi"
            limits:
              cpu: "1000m"
              memory: "1500Mi"
          envFrom:
            - configMapRef:
                name: mi-configmap   # <-- OJO: indentado debajo de configMapRef
            - secretRef:
                name: mi-secret
---
apiVersion: v1
kind: Service
metadata:
  name: mi-servicio
  namespace: gustavoc
spec:
  selector:
    app: mi-app
  ports:
    - protocol: TCP
      port: 4000        # Puerto del Service
      targetPort: 3000  # Puerto del contenedor
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mi-configmap
  namespace: gustavoc
data:
  DATABASE: "192.168.1.1" 

---
apiVersion: v1
kind: Secret
metadata:
  name: mi-secret
  namespace: gustavoc
type: Opaque
data:
  PASSWORD: 'aG9sYQo='

--- 
apiVersion: autoscaling/v2
kind: horizontalpodautoscalers
metadata:
  name: mi-hpa
  namespace: gustavoc
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: deployment
    name: mi-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 100